In [1]:
print("SHEKHALIYA SALONI DHARMESHBHAI.")

SHEKHALIYA SALONI DHARMESHBHAI.


In [2]:
import numpy as np

In [3]:
type([1,2,3,4])

list

In [5]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a=[[1,2,3],[4,5,6]]
type(a)

list

In [9]:
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
c=[[[1,2,3],[4,5,6],[7,8,9]]]
type(c)

list

In [11]:
d=np.array(c)
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
c=[[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]]
type(c)

list

In [13]:
e=np.array(c)
print(e)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [14]:
f=[[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]]]
type(f)

list

In [15]:
g=np.array(f)
print(g)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]


In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros(((3,2,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [23]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [25]:
np.random.rand(3,5)

array([[0.43822008, 0.41057692, 0.18605991, 0.97500316, 0.30870563],
       [0.07612431, 0.010152  , 0.97360642, 0.59724795, 0.95036677],
       [0.12859794, 0.42776376, 0.51180699, 0.93935711, 0.23448711]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [32]:
np.save("new_array",a)

In [33]:
np.load("new_array.npy")

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b.size

6

In [39]:
b.shape

(2, 3)

In [40]:
b.dtype

dtype('int32')

In [41]:
np.copy(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b.view(dtype='float32')

array([[1.e-45, 3.e-45, 4.e-45],
       [6.e-45, 7.e-45, 8.e-45]], dtype=float32)

In [46]:
b.view(dtype='int32')

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b.sort()

In [48]:
print(b)

[[1 2 3]
 [4 5 6]]


In [49]:
h=[[1,3,2],[6,5,4]]
type(h)

list

In [50]:
h.sort()

In [51]:
print(h)

[[1, 3, 2], [6, 5, 4]]


In [52]:
r=np.array(h)
print(r)

[[1 3 2]
 [6 5 4]]


In [53]:
r.sort()

In [54]:
print(r)

[[1 2 3]
 [4 5 6]]


In [72]:
i=[1,3,2],[6,5,4],[9,7,8]
type(i)

tuple

In [73]:
j=np.array(i)
type(j)
j.ndim
j

array([[1, 3, 2],
       [6, 5, 4],
       [9, 7, 8]])

In [75]:
j.sort(axis=1)
j

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
print(j)

[[[1 3 2]
  [6 5 4]
  [9 7 8]]]


In [60]:
j.sort(axis=1)

In [61]:
print(j)

[[[1 3 2]
  [6 5 4]
  [9 7 8]]]


In [62]:
type(j)

numpy.ndarray

In [65]:
print(y)

None


In [76]:
k=[[10,13,15],[6,3,4],[8,7,4]]

In [77]:
l=np.array(k)
type(l)

numpy.ndarray

In [78]:
print(l)


[[10 13 15]
 [ 6  3  4]
 [ 8  7  4]]


In [79]:
l.sort(axis=0)

In [80]:
print(l)

[[ 6  3  4]
 [ 8  7  4]
 [10 13 15]]


In [81]:
l.sort(axis=1)

In [82]:
print(l)

[[ 3  4  6]
 [ 4  7  8]
 [10 13 15]]


In [83]:
l.reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [84]:
array.reshape(2,3)

NameError: name 'array' is not defined

In [86]:
r.shape

(2, 3)

In [89]:
r.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.append(l,16)

array([ 3,  4,  6,  4,  7,  8, 10, 13, 15, 16])

In [91]:
np.insert(l,4,20)

array([ 3,  4,  6,  4, 20,  7,  8, 10, 13, 15])

In [92]:
np.insert(l,2,21)

array([ 3,  4, 21,  6,  4,  7,  8, 10, 13, 15])

In [94]:
np.delete(l,2,axis=0)

array([[3, 4, 6],
       [4, 7, 8]])

In [96]:
np.delete(l,1,axis=1)

array([[ 3,  6],
       [ 4,  8],
       [10, 15]])

In [98]:
np.concatenate((l,r),axis=0)

array([[ 3,  4,  6],
       [ 4,  7,  8],
       [10, 13, 15],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [99]:
np.concatenate((l,r),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [2]:
import numpy as np


In [3]:
b8=np.array([1,2,3,4,5,6])
np.split(b8,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [4]:
b8[0]=11

In [5]:
print(b8)

[11  2  3  4  5  6]


In [6]:
b8[2]

3

In [7]:
b8[0:4]

array([11,  2,  3,  4])

In [8]:
b8[:2]

array([11,  2])

In [9]:
b6=np.array([[1,2,3],[4,5,6]])
b7=np.array([[7,8,9],[10,11,12]])
np.concatenate((b6,b7),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
b6[1,2]=25
print(b6)

[[ 1  2  3]
 [ 4  5 25]]


In [11]:
b6[1,1]


5

In [12]:
b6[0:2,2]

array([ 3, 25])

In [13]:
b6[:,1]

array([2, 5])

In [14]:
np.add(b6,b7)

array([[ 8, 10, 12],
       [14, 16, 37]])

In [15]:
np.subtract(b6,b7)

array([[-6, -6, -6],
       [-6, -6, 13]])

In [16]:
np.multiply(b6,b7)

array([[  7,  16,  27],
       [ 40,  55, 300]])

In [17]:
np.divide(b6,b7)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 2.08333333]])

In [18]:
np.exp(b6)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 7.20048993e+10]])

In [19]:
np.sqrt(b7)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [20]:
b6==b7

array([[False, False, False],
       [False, False, False]])

In [21]:
np.array_equal(b6,b7)

False

In [22]:
b6.sum()

40

In [23]:
b6.min()


1

In [24]:
b6.max(axis=0)

array([ 4,  5, 25])

In [25]:
b6.max(axis=1)

array([ 3, 25])

In [26]:
b6.mean()

6.666666666666667

In [28]:
b6.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'